### ISSUE TITLE
KSP 1.2. text render

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#596]
![screenshot254](https://cloud.githubusercontent.com/assets/6713671/19309838/1204168e-90a9-11e6-94d9-d0b0e98d53b0.png)

![screenshot255](https://cloud.githubusercontent.com/assets/6713671/19309814/f7856a74-90a8-11e6-9c36-05acc4cb0515.png)

![screenshot256](https://cloud.githubusercontent.com/assets/6713671/19309815/f9917380-90a8-11e6-8f1a-a5b3c31b7e4f.png)

**Comment by MOARdV** [comment]
Something must have changed with the new shaders.  I didn't notice that in Avionics Systems, so I'll have to see what is different.

**Comment by MOARdV** [comment]
The AssetBundle export for RPM had the wrong font sizes.  Fixed in 28.1, but you can use this replacement on [DropBox](https://www.dropbox.com/s/t1c29q5dmp42wfp/rasterpropmonitor.ksp?dl=0) so you don't have to wait.  Goes in GameData/JSI/RasterPropMonitor

**Comment by Alexustas** [comment]
In the 'RasterPropMonitor v0.28.0 beta 3' this issue is back

![2016-11-06 20-23-26-691](https://cloud.githubusercontent.com/assets/6713671/20038521/58d0f874-a45f-11e6-9f68-95dad25a1a30.jpg)

**Comment by MOARdV** [comment]
I do not understand why this is happening in the screen shots.  The asset bundle is the same one I posted 3 weeks ago.  I will look at it some more here.

**Comment by Alexustas** [comment]
It seems, it's my fault. I messed with the versions. in this case, a greater version number does not mean that it is the most recent. Sorry for the confusion. You can close this issue

**Comment by MOARdV** [comment]
> It seems, it's my fault. I messed with the versions. in this case, a greater version (build) number does not mean that it is the most recent.

Yes, the way Visual Studio numbers builds is confusing, and I made it worse by using those numbers for the releases.  Sorry about that - I will use "beta No" from now on.

**Comment by Alexustas** [comment]
Alpha-channel problem 

decimal point

![2016-11-08 02-19-19-960](https://cloud.githubusercontent.com/assets/6713671/20130724/f9bbde46-a682-11e6-83f2-2e986ee422ae.jpg)

![2016-11-08 02-19-31-278](https://cloud.githubusercontent.com/assets/6713671/20130728/fe4a1716-a682-11e6-99d7-52da7aa1a371.jpg)

**Comment by MOARdV** [comment]
That looks like it may be a depth problem - I will go look at the shader and see what I did.

**Comment by MOARdV** [comment]
I checked the shader again, and it is correctly doing premultiplied alpha.  There is no depth test enabled, so I do not know yet why alpha is wrong on this display.  I will have to do some more searching.

**Comment by Alexustas** [comment]
also there is a strange behavior of transparency. it's more like an alpha-cutoff mode

a series of  zeros has the color 0,255,0,80:

![2016-11-13 16-09-16-598](https://cloud.githubusercontent.com/assets/6713671/20244886/ce35297a-a9bc-11e6-83a6-334c092384f5.jpg)

**Comment by Alexustas** [comment]
if I change the color to 0,255,0,**70** the zeros disappear completely

![2016-11-13 16-22-35-808](https://cloud.githubusercontent.com/assets/6713671/20244907/86126652-a9bd-11e6-9669-5568761aca35.jpg)

**Comment by Alexustas** [comment]
in earlier versions of RPM everything worked correctly. 

![2016-08-11 02-54-16-287](https://cloud.githubusercontent.com/assets/6713671/20244927/071c974a-a9be-11e6-8e0c-619cfef1e1dc.jpg)

but now I can not say exactly when it broke

**Comment by MOARdV** [comment]
Okay.  I did not see anything in the shader when I looked.  I will check again.
